;CONVERT BINARY TO HEXADECIMAL


INCLUDE "EMU8086.INC"
.MODEL SMALL
.STACK 100H
.DATA

MAIN PROC 
    
MOV AX,@DATA     ;GET DATA SEGMENT
MOV DS,AX        ;INITIALIZE DS 


MOV CX,16        ;MOVE VALUE INTO CX
XOR BX,BX        ;CLEAR BX
MOV AH,1         ;INPUT CHARECTER FUNCTION 
PRINT 'ENTER A BINARY NUMBER:  '

WHILE:
INT 21H          ;READ A CHARECTER
CMP AL,0DH       ;CARRY RETURN
JE END_WHILE     ;YES, DONE
AND AL,0FH       ;CONVERT TO BINARY VALUE
SHL BX,1         ;MAKE ROOM FOR NEW VALUE
OR BL,AL         ;PUT VALUE INTO BX
JMP WHILE

END_WHILE:


PRINTN
PRINT 'EQUIVALENT HEXADECIMAL NUMBER:  '
MOV CX,4         ;COUNTER FOR 4 SHIFTS
XOR DX,DX        ;CLEAR DX
                 

LOOP3:

MOV DL,BH        ;MOVE VALUE BH TO DL
SHR DL,4         ;SHIFT RIGHT 4 TIMES

CMP DL,9         ;IF NUMBER?
JLE NUMBER3

CMP DL,15        ;IF LETTER?
JLE LETTER3

NUMBER3:         ;CONVERT IN NUMBER
ADD DL,48
MOV AH,2
INT 21H
JMP CLEAR

LETTER3:         ;CONVERT IN LETTER
ADD DL,55
MOV AH,2
INT 21H
JMP CLEAR

CLEAR:           ;ROTATE LEFT 4 TIMES
ROL BX,4

LOOP LOOP3



EXIT:            ;EXIT DOS
MOV AX,4CH
INT 21H
MAIN ENDP
END MAIN